#!/bin/sh

set -e

STAMP=/var/lib/update-notifier/dpkg-run-stamp

if [ ! -f $STAMP ]; then
	touch $STAMP
fi

# fixup /var/crash permissions (#449739)
if [ "$1" = configure ] && dpkg --compare-versions "$2" le-nl "0.89"; then
    if [ -d /var/crash ] && [ "$(stat -L -c '%a' /var/crash)" = "755" ]; then
        chmod 1777 /var/crash
    fi
fi

#DEBHELPER#
